mode: train
#mode: test
#mode: render_depth_sequences

train:
  data:
    subject_name: my_313
    data_dir: 'data/my_zju_mocap/my_313'
    # frame_range: [0, 1, 1]
    frame_range: [0, 60, 1]
    used_cam_ids: [0, 6, 12, 18]
    # used_cam_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    # use_zjumocap: True
  net_ckpt_dir: 'data/results/my_313'
  # prev_ckpt: data/results/my_313/epoch_latest
  prev_ckpt: data/results/my_313/epoch_40
  save_init_ckpt: false
  start_epoch: 40
  end_epoch: 100
  ckpt_interval:
    epoch: 1
    batch: 10000
  eval_interval: 10000

  # nerf-related
  depth_guided_sampling:
    flag: true
    near_sur_dist: 0.05
    N_ray_samples: 32
  compute_grad: true
  ray_sampling: # ray sampling method on training images
    epoch_ranges: [[0, 9999], [9999, 999999]]
    schedules: ['random', 'patch']
    type: null
    patch:
      patch_num: 1
      patch_size: 64
      inside_radio: 1.0
    random:
      sample_num: 1024
      inside_radio: 0.8
  lr:
    network:
      type: 'Step'
      initial: 0.0005
      interval: 40000
      factor: 0.9
      min: 0.00008
  loss_weight:
    color: 1.0
    lpips: 1.0
    mask: 1.0
    eikonal: 0.1
    tv: 10.0
  batch_size: 8
  num_workers: 0
test:
  data:
    data_dir: 'data/my_zju_mocap/my_313'
    used_cam_ids: [3, 9, 15]
    frame_range: [60, 120, 20]
    frame_win: 2
    fix_head_pose: false
    use_zjumocap: True

  pose_data:
    data_path: 'data/my_zju_mocap/my_313/smpl_params.npz'
    frame_range: [60, 120, 20]
    frame_win: 2
    # use_zjumocap: True

  # render view setting
  view_setting: 'free'  # 'free' or 'camera'
  render_view_idx: 18
  global_orient: true
  img_scale: 1.0

  vol_res: [128, 128, 128]
  depth_guided_sampling:
    flag: true
    near_sur_dist: 0.02
    N_ray_samples: 16
  infer_rgb: true
  save_mesh: false
  render_skeleton: true
  prev_ckpt: 'data/results/my_313/epoch_40'

model:
  local_pose: true
  multires: 6

  use_viewdir: false
  multires_viewdir: 3

  multiscale_line_sizes:
    - [8, 8, 2]
    - [32, 32, 8]
    - [128, 128, 32]
    - [256, 256, 64]
  feat_dims:
    - 4
    - 4
    - 4
    - 4
  point_nums:
    - 256
    - 256
    - 256
    - 256
  knns:
    - 10
    - 10
    - 10
    - 10
  pose_formats:
    - 'quaternion'
    - 'quaternion'
    - 'quaternion'
    - 'quaternion'
  concat_pose_vec: true
